"""
Database models and session management for SentinelWatch SIEM.
Supports SQLite (default) with upgrade path to PostgreSQL.
"""

from sqlalchemy import create_engine, Column, String, Integer, DateTime, Float, Text, Boolean
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from datetime import datetime
import os

# PostgreSQL for AWS Amplify
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./sentinelwatch.db")

# Create engine
if DATABASE_URL.startswith("sqlite"):
    engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
elif DATABASE_URL.startswith("postgresql"):
    engine = create_engine(DATABASE_URL, pool_pre_ping=True, pool_recycle=300)
else:
    engine = create_engine(DATABASE_URL)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


class LogEntry(Base):
    """
    Normalized log entry stored in database.
    Common schema: timestamp, source IP, username, event type, status.
    """
    __tablename__ = "log_entries"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, index=True, nullable=False)
    source_ip = Column(String(45), index=True)  # IPv6 compatible
    username = Column(String(255), index=True)
    event_type = Column(String(100), index=True)  # e.g., "login", "privilege_escalation", "system_event"
    status = Column(String(50), index=True)  # e.g., "success", "failed", "denied"
    raw_log = Column(Text)  # Original log line
    source_file = Column(String(500))  # Original file name if uploaded
    country_code = Column(String(2))  # ISO country code from geolocation
    latitude = Column(Float)
    longitude = Column(Float)
    created_at = Column(DateTime, default=datetime.utcnow)


class Alert(Base):
    """
    Structured alert generated by detection rules.
    Contains unique ID, rule name, severity, context, and timestamps.
    """
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    alert_id = Column(String(36), unique=True, index=True)  # UUID
    rule_name = Column(String(100), index=True)
    severity = Column(String(20), index=True)  # Low, Medium, High, Critical
    description = Column(Text, nullable=False)
    context = Column(Text)  # JSON string with additional context
    source_ip = Column(String(45), index=True)
    username = Column(String(255), index=True)
    log_entry_id = Column(Integer)  # Reference to related log entry
    triggered_at = Column(DateTime, default=datetime.utcnow, index=True)
    acknowledged = Column(Boolean, default=False)
    resolved = Column(Boolean, default=False)
    notes = Column(Text)  # Analyst notes/comments
    acknowledged_by = Column(String(255))  # Who acknowledged
    resolved_by = Column(String(255))  # Who resolved
    acknowledged_at = Column(DateTime)
    resolved_at = Column(DateTime)


class DetectionRule(Base):
    """
    Detection rules configuration.
    Stores rule metadata and configuration.
    """
    __tablename__ = "detection_rules"

    id = Column(Integer, primary_key=True, index=True)
    rule_name = Column(String(100), unique=True, nullable=False)
    rule_type = Column(String(50))  # regex, correlation, geolocation, etc.
    severity = Column(String(20))
    enabled = Column(Boolean, default=True)
    description = Column(Text)
    configuration = Column(Text)  # JSON string with rule config
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


# Create all tables
def init_db():
    """Initialize database tables."""
    Base.metadata.create_all(bind=engine)


# Dependency for FastAPI
def get_db():
    """Database session dependency for FastAPI."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()



